'use client';

import { useState } from 'react';
import { useFormState, useFormStatus } from 'react-dom';
import {
  ChevronDown, ChevronUp, PlayCircle, ExternalLink,
  Bot, Info, Send, CheckCircle2, AlertCircle, Loader2,
} from 'lucide-react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import {
  Tooltip, TooltipTrigger, TooltipContent, TooltipProvider,
} from '@/components/ui/tooltip';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { submitTranscriptCorrection, type CorrectionState } from '@/app/actions/speech-pipeline';
import { FlagButton } from '@/components/moderation/flag-button';
import type { Speech } from '@/types';

// ── Types ─────────────────────────────────────────────────────────────────────

type TranscriptLocale = 'en' | 'ha' | 'yo' | 'ig';

const LOCALE_LABELS: Record<TranscriptLocale, string> = {
  en: 'English',
  ha: 'Hausa',
  yo: 'Yorùbá',
  ig: 'Igbo',
};

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Extract YouTube video ID from various YouTube URL formats. */
function getYouTubeId(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.hostname.includes('youtube.com')) return u.searchParams.get('v');
    if (u.hostname === 'youtu.be') return u.pathname.slice(1).split('?')[0];
  } catch {
    // not a valid URL
  }
  return null;
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-NG', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
}

// ── AI badge + tooltip ────────────────────────────────────────────────────────

function AiBadge({
  locale,
  speechId,
}: {
  locale: TranscriptLocale;
  speechId: string;
}) {
  const [correctionOpen, setCorrectionOpen] = useState(false);

  const tooltipText =
    locale === 'en'
      ? 'This transcript was automatically generated by OpenAI Whisper and may contain errors.'
      : 'This translation was generated by Claude AI and may contain errors.';

  return (
    <>
      <span className="inline-flex items-center gap-1.5">
        <Tooltip>
          <TooltipTrigger asChild>
            <span
              className={cn(
                'inline-flex cursor-default items-center gap-1 rounded-full border px-2 py-0.5',
                'text-[10px] font-semibold uppercase tracking-wide',
                'border-violet-200 bg-violet-50 text-violet-700',
                'dark:border-violet-800 dark:bg-violet-950/40 dark:text-violet-300',
              )}
            >
              <Bot className="h-2.5 w-2.5" />
              {locale === 'en' ? 'AI-transcribed' : 'AI-translated'}
              <Info className="h-2.5 w-2.5 opacity-60" />
            </span>
          </TooltipTrigger>
          <TooltipContent className="max-w-[260px] space-y-1.5">
            <p>{tooltipText}</p>
            <p>
              Help us improve —{' '}
              <button
                onClick={() => setCorrectionOpen(true)}
                className="underline underline-offset-2 hover:text-foreground"
              >
                submit a correction
              </button>
              .
            </p>
          </TooltipContent>
        </Tooltip>
      </span>

      <CorrectionModal
        open={correctionOpen}
        onClose={() => setCorrectionOpen(false)}
        speechId={speechId}
        locale={locale}
      />
    </>
  );
}

// ── Correction modal ──────────────────────────────────────────────────────────

function CorrectionSubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" size="sm" disabled={pending} className="gap-2">
      {pending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Send className="h-3.5 w-3.5" />}
      {pending ? 'Submitting…' : 'Submit correction'}
    </Button>
  );
}

function CorrectionModal({
  open,
  onClose,
  speechId,
  locale,
}: {
  open: boolean;
  onClose: () => void;
  speechId: string;
  locale: TranscriptLocale;
}) {
  const initial: CorrectionState = { status: 'idle', message: '' };
  const [state, formAction] = useFormState(submitTranscriptCorrection, initial);

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Submit a transcript correction</DialogTitle>
          <DialogDescription>
            Found an error in the {LOCALE_LABELS[locale]} transcript? Paste the
            corrected text below. Our team will review and apply it.
          </DialogDescription>
        </DialogHeader>

        {state.status === 'success' ? (
          <div className="flex flex-col items-center gap-3 py-6 text-center">
            <CheckCircle2 className="h-10 w-10 text-green-500" />
            <p className="font-medium">Thank you!</p>
            <p className="text-sm text-muted-foreground">{state.message}</p>
            <Button variant="outline" size="sm" onClick={onClose}>
              Close
            </Button>
          </div>
        ) : (
          <form action={formAction} className="space-y-4">
            <input type="hidden" name="speechId" value={speechId} />
            <input type="hidden" name="locale" value={locale} />

            <div className="space-y-1.5">
              <label htmlFor="correction" className="text-sm font-medium">
                Corrected text{' '}
                <span className="text-muted-foreground text-xs">
                  ({LOCALE_LABELS[locale]})
                </span>
              </label>
              <textarea
                id="correction"
                name="correction"
                required
                minLength={10}
                rows={6}
                placeholder={`Paste the corrected ${LOCALE_LABELS[locale]} transcript here…`}
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-y"
              />
            </div>

            <div className="space-y-1.5">
              <label htmlFor="correctionEmail" className="text-sm font-medium">
                Email{' '}
                <span className="text-muted-foreground text-xs">(optional — for follow-up)</span>
              </label>
              <input
                id="correctionEmail"
                name="email"
                type="email"
                placeholder="you@example.com"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>

            {state.status === 'error' && (
              <p className="flex items-center gap-2 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">
                <AlertCircle className="h-3.5 w-3.5 shrink-0" />
                {state.message}
              </p>
            )}

            <div className="flex justify-end gap-2">
              <Button type="button" variant="ghost" size="sm" onClick={onClose}>
                Cancel
              </Button>
              <CorrectionSubmitButton />
            </div>
          </form>
        )}
      </DialogContent>
    </Dialog>
  );
}

// ── Audio player ──────────────────────────────────────────────────────────────

function AudioPlayer({ speechId }: { speechId: string }) {
  return (
    <div className="rounded-lg border bg-muted/20 px-3 py-2.5">
      <p className="mb-2 text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
        Audio recording
      </p>
      {/* Signed URL is generated server-side via the /api/speeches/[id]/audio route. */}
      {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
      <audio
        controls
        preload="metadata"
        src={`/api/speeches/${speechId}/audio`}
        className="w-full h-10"
      />
    </div>
  );
}

// ── Transcript panel ──────────────────────────────────────────────────────────

function TranscriptPanel({
  speech,
  defaultLocale,
}: {
  speech: Speech;
  defaultLocale: TranscriptLocale;
}) {
  const [show, setShow]               = useState(false);
  const [transcriptLocale, setLocale] = useState<TranscriptLocale>(defaultLocale);

  const transcriptKey = `transcript_${transcriptLocale}` as
    | 'transcript_en' | 'transcript_ha' | 'transcript_yo' | 'transcript_ig';
  const transcript = speech[transcriptKey];

  const availableLocales = (['en', 'ha', 'yo', 'ig'] as TranscriptLocale[]).filter((l) => {
    const key = `transcript_${l}` as typeof transcriptKey;
    return !!speech[key];
  });

  if (availableLocales.length === 0) return null;

  return (
    <div>
      <button
        onClick={() => setShow((v) => !v)}
        className="flex w-full items-center justify-between rounded-md border px-3 py-2 text-sm font-medium hover:bg-muted transition-colors"
      >
        Read transcript
        {show ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
      </button>

      {show && (
        <div className="mt-3 space-y-3">
          {/* Language switcher */}
          {availableLocales.length > 1 && (
            <div className="flex flex-wrap gap-1">
              {availableLocales.map((l) => (
                <button
                  key={l}
                  onClick={() => setLocale(l)}
                  className={cn(
                    'rounded-full px-3 py-1 text-xs font-medium transition-colors',
                    transcriptLocale === l
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
                  )}
                >
                  {LOCALE_LABELS[l]}
                </button>
              ))}
            </div>
          )}

          {/* AI badge (shown when AI-generated) */}
          {speech.ai_translated && (
            <TooltipProvider delayDuration={200}>
              <AiBadge locale={transcriptLocale} speechId={speech.id} />
            </TooltipProvider>
          )}

          {/* Transcript body */}
          {transcript ? (
            <div className="group relative rounded-md bg-muted/50 p-4 text-sm leading-relaxed whitespace-pre-line max-h-80 overflow-y-auto">
              {transcript}
              {/* Flag button — visible on hover, positioned top-right of panel */}
              <FlagButton
                contentType="speech"
                contentId={speech.id}
                className="sticky top-0 float-right ml-2"
              />
            </div>
          ) : (
            <p className="text-xs italic text-muted-foreground">
              No transcript available in {LOCALE_LABELS[transcriptLocale]}.
            </p>
          )}
        </div>
      )}
    </div>
  );
}

// ── Processing status banner ──────────────────────────────────────────────────

function PipelineStatusBanner({ status, error }: {
  status: Speech['transcription_status'];
  error: string | null;
}) {
  if (status === 'none' || status === 'done') return null;

  if (status === 'processing') {
    return (
      <div className="flex items-center gap-2 rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-700 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-300">
        <Loader2 className="h-3.5 w-3.5 animate-spin shrink-0" />
        Transcription in progress — check back in a moment.
      </div>
    );
  }

  return (
    <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-300">
      <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
      <span>
        Transcription failed.{error ? ` Error: ${error}` : ''} Retry from the admin panel.
      </span>
    </div>
  );
}

// ── Speech card ───────────────────────────────────────────────────────────────

function SpeechCard({
  speech,
  defaultLocale,
}: {
  speech: Speech;
  defaultLocale: TranscriptLocale;
}) {
  const youtubeId = speech.video_url ? getYouTubeId(speech.video_url) : null;

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="space-y-1">
          <h3 className="font-semibold leading-snug">{speech.title}</h3>
          <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
            <span>{formatDate(speech.date)}</span>
            {speech.source && <span>· {speech.source}</span>}
            {speech.tags.length > 0 && (
              <span className="flex flex-wrap gap-1">
                ·
                {speech.tags.map((t) => (
                  <span
                    key={t}
                    className="inline-block rounded-full bg-secondary px-2 py-0.5 text-secondary-foreground"
                  >
                    {t}
                  </span>
                ))}
              </span>
            )}
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* ── Pipeline status ── */}
        <PipelineStatusBanner
          status={speech.transcription_status}
          error={speech.transcription_error}
        />

        {/* ── Audio player (uploaded file) ── */}
        {speech.audio_storage_path && (
          <AudioPlayer speechId={speech.id} />
        )}

        {/* ── Video embed (YouTube or link) ── */}
        {youtubeId ? (
          <div className="aspect-video w-full overflow-hidden rounded-lg bg-black">
            <iframe
              src={`https://www.youtube.com/embed/${youtubeId}`}
              title={speech.title}
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
              className="h-full w-full"
            />
          </div>
        ) : speech.video_url ? (
          <a
            href={speech.video_url}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 rounded-lg border p-3 text-sm hover:bg-muted transition-colors"
          >
            <PlayCircle className="h-5 w-5 text-primary" />
            Watch video
            <ExternalLink className="ml-auto h-4 w-4 text-muted-foreground" />
          </a>
        ) : null}

        {/* ── Transcript panel ── */}
        <TranscriptPanel speech={speech} defaultLocale={defaultLocale} />
      </CardContent>
    </Card>
  );
}

// ── Tab root ──────────────────────────────────────────────────────────────────

interface Props {
  speeches: Speech[];
  currentLocale: string;
}

export function SpeechesTab({ speeches, currentLocale }: Props) {
  const defaultLocale = (['en', 'ha', 'yo', 'ig'] as TranscriptLocale[]).includes(
    currentLocale as TranscriptLocale,
  )
    ? (currentLocale as TranscriptLocale)
    : 'en';

  if (!speeches.length) {
    return (
      <div className="rounded-lg border bg-muted/30 p-8 text-center text-sm text-muted-foreground">
        <p className="font-medium">No speeches recorded yet.</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {speeches.map((speech) => (
        <SpeechCard key={speech.id} speech={speech} defaultLocale={defaultLocale} />
      ))}
    </div>
  );
}
