/**
 * Sample Nigerian election news articles shown when no live data exists.
 * These are realistic placeholder articles for demo purposes.
 */

import type { NewsArticle } from '@/types';

export const SAMPLE_ARTICLES: NewsArticle[] = [
  {
    id: 'sample-001',
    title: 'INEC Confirms 2027 General Elections Timetable, Releases Registration Deadlines',
    description: 'The Independent National Electoral Commission has officially confirmed key dates for the 2027 general elections, urging eligible Nigerians to register before the deadline.',
    url: 'https://punchng.com/inec-confirms-2027-elections-timetable',
    source_name: 'Punch Nigeria',
    author: 'Chioma Umeha',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'INEC has released the official timetable for the 2027 general elections, with voter registration closing six months before polling day. The commission emphasized the importance of youth participation and clean electoral rolls.',
    candidates_mentioned: [],
    policy_tags: ['election process', 'governance'],
    sentiment: 'neutral',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-002',
    title: 'APC, PDP Begin Internal Consultations Ahead of 2027 Presidential Race',
    description: 'Both major political parties have commenced internal meetings to identify potential flagbearers for the 2027 presidential election as jostling intensifies across political circles.',
    url: 'https://thecable.ng/apc-pdp-2027-presidential-consultations',
    source_name: 'TheCable',
    author: 'Samuel Oyekanmi',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'Nigeria\'s two dominant parties, APC and PDP, have begun behind-the-scenes consultations to line up presidential candidates for 2027. Party insiders say zoning formulas and regional considerations will play a major role in the final selections.',
    candidates_mentioned: [],
    policy_tags: ['governance', 'election process'],
    sentiment: 'neutral',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-003',
    title: 'Economy Tops Voter Concerns Ahead of 2027 Elections, Survey Shows',
    description: 'A new survey by the Centre for Democracy and Development reveals that over 68% of Nigerians rank economic management as their top concern when choosing their 2027 presidential candidate.',
    url: 'https://vanguardngr.com/economy-tops-voter-concerns-2027',
    source_name: 'Vanguard',
    author: 'Babajide Komolafe',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'A CDD survey of 4,500 Nigerian voters shows the economy is the defining issue of the 2027 election cycle, with inflation, unemployment, and naira stability all cited as top concerns. Security came in second at 54%, followed by education at 41%.',
    candidates_mentioned: [],
    policy_tags: ['economy', 'governance', 'election process'],
    sentiment: 'neutral',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-004',
    title: 'Governors Forum Debates Federal Character Principle for 2027 Presidency',
    description: 'The Nigeria Governors Forum met in Abuja to discuss how the federal character principle should guide the choice of presidential and vice-presidential candidates for the upcoming 2027 election.',
    url: 'https://dailytrust.com/governors-forum-federal-character-2027',
    source_name: 'Daily Trust',
    author: 'Levi Obijiofor',
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'Nigeria\'s 36 state governors gathered to debate the application of the federal character principle to 2027 presidential nominations. North-South rotational arguments dominated proceedings, with no consensus reached on the preferred formula.',
    candidates_mentioned: [],
    policy_tags: ['governance', 'election process'],
    sentiment: 'mixed',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-005',
    title: 'Civil Society Groups Launch Voter Education Drive Targeting 10 Million New Registrants',
    description: 'A coalition of 45 Nigerian civil society organisations has kicked off a nationwide voter registration drive targeting young Nigerians between 18 and 30, aiming to add 10 million new voters before 2027.',
    url: 'https://premiumtimesng.com/civil-society-voter-education-2027',
    source_name: 'Premium Times',
    author: 'Ijeoma Nwogwugwu',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'A 45-organisation civil society coalition has launched a 24-month voter education and registration campaign targeting Nigerian youth. The drive aims to register 10 million new voters before the 2027 election cycle begins.',
    candidates_mentioned: [],
    policy_tags: ['election process', 'youth', 'governance'],
    sentiment: 'positive',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-006',
    title: 'Senate Debates Electoral Act Amendments Ahead of 2027 Cycle',
    description: 'The Nigerian Senate is considering amendments to the Electoral Act that would tighten campaign finance rules and introduce electronic result transmission as a mandatory requirement nationwide.',
    url: 'https://nta.ng/senate-electoral-act-amendments-2027',
    source_name: 'NTA',
    author: 'Ngozi Okafor',
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'Nigeria\'s Senate is reviewing proposed Electoral Act amendments that would cap campaign spending and mandate electronic collation of results across all polling units. Critics warn implementation timelines are too ambitious given infrastructure gaps.',
    candidates_mentioned: [],
    policy_tags: ['election process', 'governance', 'corruption'],
    sentiment: 'mixed',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-007',
    title: 'Infrastructure Deficit Emerges as Key Campaign Battleground for 2027',
    description: 'With road networks, power supply, and water access still critically underfunded, analysts say any credible 2027 presidential candidate must present a costed infrastructure plan to be taken seriously.',
    url: 'https://businessday.ng/infrastructure-2027-campaign-battleground',
    source_name: 'BusinessDay',
    author: 'Frank Eleanya',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'Political analysts and economists say Nigeria\'s chronic infrastructure deficit — estimated at $3 trillion over 30 years — will be the defining policy battleground of the 2027 campaign. Candidates who fail to present credible funding plans risk losing swing voters in the South-West and South-East.',
    candidates_mentioned: [],
    policy_tags: ['infrastructure', 'economy', 'energy'],
    sentiment: 'neutral',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sample-008',
    title: 'Security Crisis in North-East Puts Defence Policy at Centre of 2027 Debate',
    description: 'Renewed Boko Haram activity in Borno and Yobe states has forced defence and security policy back onto the 2027 election agenda, with presidential hopefuls expected to articulate comprehensive counter-terrorism strategies.',
    url: 'https://saharareporters.com/security-north-east-2027-debate',
    source_name: 'Sahara Reporters',
    author: 'Omoyele Sowore',
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
    ai_summary: 'Escalating insecurity in Nigeria\'s North-East has made defence policy a central 2027 election issue. Analysts expect candidates to face tough questions on military spending, community policing, and how to reintegrate former combatants into civilian life.',
    candidates_mentioned: [],
    policy_tags: ['security', 'governance'],
    sentiment: 'negative',
    ai_enriched_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
